# Used only to generate requirements file for different components in Kadalu
[metadata]
name = Kadalu
description = Used only for generating python package requirements in various Dockerfiles under this repo
author_email = engineering@kadalu.io
url = https://github.com/kadalu/kadalu

[options]
python_requires = >=3.10

[options.extras_require]
# run "make gen-requirements" to generate all requirements files
builder = pip; setuptools; prometheus-client>=0.21.0; jinja2>=3.1.4; requests>=2.32.0; datetime; xxhash; fastapi>=0.115.0; urllib3>=2.2.0; uvicorn[standard]
operator = kubernetes>=29.0.0;
csi = googleapis-common-protos>=1.63.0; protobuf>=5.26.0; pyxattr>=0.8.1; grpcio>=1.63.0;
server = pyxattr>=0.8.1;
ci_submit = pylint; glustercli
ci_merge = kubernetes>=29.0.0; jinja2>=3.1.4; twine; xxhash; grpcio>=1.63.0; pyxattr>=0.8.1; pytest
